version: "3.8"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    command: --auth
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongodb
    build: .
    container_name: rest-api-application
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=$DB_LOCAL_PORT
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    

    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
 
  

volumes: 
  db: {}
  